Repository LIKELION-Android-Bootcamp-4th/MansBath, pull requests merged in 2025-08, with the labels that each got.

#2 질문 생성
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/home/ChatModel.kt
  app/src/main/java/com/aspa/aspa/features/home/DummyData.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeDrawerContent.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeScreen.kt
  app/src/main/java/com/aspa/aspa/features/home/components/ChatComponents.kt
  app/src/main/java/com/aspa/aspa/features/home/components/InitialContent.kt
  app/src/main/java/com/aspa/aspa/features/home/components/UserInput.kt
  gradle/libs.versions.toml
Labels: ui

#9 [ui/Q03]퀴즈 결과 화면
  app/src/main/java/com/aspa/aspa/features/quiz/QuizResultDummy.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizResultScreen.kt
  app/src/main/java/com/aspa/aspa/model/Quiz.kt
Labels: ui

#4 [ui/Q01]퀴즈 목록 페이지 UI
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/quiz/DummySection.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/component/QuizListCard.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/DummyData.kt
  app/src/main/java/com/aspa/aspa/model/Section.kt
Labels: ui

#19 chore: downgrade typescript to 5.1.6
  firebase/functions/package-lock.json
  firebase/functions/package.json
Labels: firebase, chore

#21 [firebase/api-key] dotenv를 이용한 api 키 추가
  firebase/functions/.gitignore
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/src/auth.ts
  firebase/functions/src/index.ts
  firebase/functions/src/question/firestore_service.ts
  firebase/functions/src/question/gen_ai.ts
  firebase/functions/src/question/gen_ai_service.ts
  firebase/functions/src/question/question.ts
  firebase/functions/src/question/types.ts
Labels: feat, firebase

#22 [firebase/fix/linebreak] linebreak 수정 및 firebase 폴더 아래 `LF` 유지
  .gitattributes
Labels: firebase, fix, chore

#29 [firebase/refactor/roadmap] roadmap.ts 리팩토링
  firebase/functions/src/ai/roadmap_prompt.ts
  firebase/functions/src/index.ts
  firebase/functions/src/roadmap/firestore_service.ts
  firebase/functions/src/roadmap/roadmap.ts
  firebase/functions/src/roadmap/validator.ts
  firebase/functions/src/type/roadmap_types.ts
  firebase/functions/src/util/formatter.ts
  firebase/functions/src/util/parser.ts
Labels: firebase, refactor

#13 [ui/main] MainScreen 내 각 탭 화면 연결 작업
  app/build.gradle.kts
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/core/constants/enums/BottomTab.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeDrawerContent.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeScreen.kt
  app/src/main/java/com/aspa/aspa/features/home/components/HomeTopBar.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/main/components/BottomNavigationBar.kt
  app/src/main/java/com/aspa/aspa/features/main/components/DefaultTopBar.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapTopBar.kt
  app/src/main/java/com/aspa/aspa/ui/components/BottomNavigation.kt
  gradle/libs.versions.toml
Labels: ui, feat

#28 [firebase/s01] AI를 통한 학습 데이터 생성 기능 구현
  .gitignore
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  firebase/.firebaserc
  firebase/functions/lib/Study/roadmap.json
  firebase/functions/package.json
  firebase/functions/src/Study/config.ts
  firebase/functions/src/Study/dummy_data.ts
  firebase/functions/src/Study/fetchfirebase_data.ts
  firebase/functions/src/Study/firestore.ts
  firebase/functions/src/Study/formetError.ts
  firebase/functions/src/Study/get_ai_response.ts
  firebase/functions/src/Study/roadmap.json
  firebase/functions/src/Study/study_entity.ts
  firebase/functions/src/index.ts
  firebase/functions/tsconfig.json
Labels: feat, firebase

#39 [ui/M01] 마이페이지 ui 구현
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
Labels: ui

#40 [feat/auth/kakao] 카카오 로그인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aspa/aspa/AspaAppliation.kt
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  build.gradle.kts
  firebase/functions/.gitignore
  firebase/functions/src/auth/auth.ts
  firebase/functions/src/auth/kakao.ts
  firebase/package-lock.json
  firebase/package.json
  settings.gradle.kts
Labels: feat

#41 [feat/auth/naver] 네이버 소셜 로그인 구현
  app/build.gradle.kts
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  build.gradle.kts
  firebase/functions/src/auth/auth.ts
  firebase/functions/src/auth/naver.ts
  firebase/functions/src/index.ts
  gradle/libs.versions.toml
Labels: feat, firebase

#42 [fix/auth/kakao] 카카오 로그인 시 firestore의 `lastLogin` 필드 업데이트 로직 추가
  app/src/main/java/com/aspa/aspa/MainActivity.kt
Labels: fix

#43 [Feature,hilt] 구글 로그인 및 hilt 적용 및 로그인 구조 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aspa/aspa/AspaAppliation.kt
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/data/dto/UserProfileDto.kt
  app/src/main/java/com/aspa/aspa/data/remote/GoogleRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/remote/UserRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/AuthRepository.kt
  app/src/main/java/com/aspa/aspa/data/repository/GoogleRepositoryImpl.kt
  app/src/main/java/com/aspa/aspa/di/FirebaseModule.kt
  app/src/main/java/com/aspa/aspa/di/GoogleSignInModule.kt
  app/src/main/java/com/aspa/aspa/di/RepositoryModule.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginViewModel.kt
  app/src/main/java/com/aspa/aspa/features/login/google/GoogleSignInClient.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feat

#44 [feat/a01] Retrofit 에서 onCall 방식으로 변경
  app/build.gradle.kts
  app/src/main/java/com/aspa/aspa/data/dto/QuestionDto.kt
  app/src/main/java/com/aspa/aspa/data/remote/QuestionRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/QuestionRepository.kt
  app/src/main/java/com/aspa/aspa/data/service/QuestionApiService.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeViewModel.kt
  app/src/main/java/com/aspa/aspa/model/Question.kt
  app/src/main/java/com/aspa/aspa/network/RetrofitProvider.kt
  firebase/functions/src/ai/question_prompt.ts
  firebase/functions/src/index.ts
  firebase/functions/src/question/question.ts
Labels: feat

#58 [fix/route/roadmap] 로드맵 라우팅 관련 fix
  app/src/main/java/com/aspa/aspa/features/home/navigation/HomeNavigation.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/main/components/BottomNavigationBar.kt
  app/src/main/java/com/aspa/aspa/features/main/navigation/MainNavigation.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapDialog.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/navigation/RoadmapNavigation.kt
Labels: fix

#69 [fix/RM_ALL] home쪽 코드 수정 및 roadmap의 uid 연동
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeViewModel.kt
  app/src/main/java/com/aspa/aspa/features/home/navigation/HomeNavigation.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapDialog.kt
  app/src/main/java/com/aspa/aspa/model/Auth.kt
Labels: fix

#70 [fix/RM_ALL] 로드맵 관련 코드 수정 및 리팩토링
  app/src/main/java/com/aspa/aspa/data/remote/RoadmapRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/RoadmapRepository.kt
  app/src/main/java/com/aspa/aspa/features/home/HomeViewModel.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/CreateStudy.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapViewModel.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapDialog.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/navigation/RoadmapNavigation.kt
  app/src/main/java/com/aspa/aspa/ui/components/StudyNav/StudyNav.kt
Labels: refactor, fix

#71 [fix/ui/roadmap] 제목과 section 진행률 간의 ui 겹침 수정
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapCard.kt
Labels: ui, fix

#74 [Feat/auth/kakao] 카카오 로그인 연결
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginViewModel.kt
Labels: feat

#79 [fix/A01] 드로워 홈 화면 처리
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
Labels: fix

#80 [fix/route/all] 전체적인 라우팅 수정
  app/src/main/java/com/aspa/aspa/MainActivity.kt
  app/src/main/java/com/aspa/aspa/features/home/navigation/HomeNavigation.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/java/com/aspa/aspa/features/login/navigation/LoginNavigation.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/main/components/BottomNavigationBar.kt
  app/src/main/java/com/aspa/aspa/features/main/navigation/MainNavigation.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/features/mypage/navigation/MypageNavigation.kt
  app/src/main/java/com/aspa/aspa/features/navigation/AppNavHost.kt
  app/src/main/java/com/aspa/aspa/features/quiz/navigation/QuizNavigation.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/navigation/RoadmapNavigation.kt
  app/src/main/java/com/aspa/aspa/util/DoubleBackExitHandler.kt
Labels: fix

#85 [fix/UI/topbar] topbar 통일
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/main/components/CommonTopBar.kt
  app/src/main/java/com/aspa/aspa/features/main/components/DefaultTopBar.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
Labels: refactor, fix

#86 [fix/Q01] 퀴즈 화면 데이터 바인딩 및 관련 이슈 수정
  app/src/main/java/com/aspa/aspa/data/dto/QuizDto.kt
  app/src/main/java/com/aspa/aspa/data/remote/QuizRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/QuizRepository.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizResultScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizViewModel.kt
  app/src/main/java/com/aspa/aspa/features/quiz/SolveQuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/component/QuizListCard.kt
  app/src/main/java/com/aspa/aspa/features/quiz/navigation/QuizNavigation.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapDialog.kt
  app/src/main/java/com/aspa/aspa/features/state/MakeQuizState.kt
  app/src/main/java/com/aspa/aspa/features/study/StudyDetail/StudyDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/study/StudyViewModel.kt
  app/src/main/java/com/aspa/aspa/model/QuizInfo.kt
  app/src/main/java/com/aspa/aspa/ui/components/StudyNav/StudyNav.kt
  firebase/functions/src/quiz/firestore_service.ts
  firebase/functions/src/quiz/gen_ai_service.ts
  firebase/functions/src/quiz/quiz.ts
  firebase/functions/src/type/quiz_types.ts
Labels: feat, fix

#91 [fix/route/generate roadmap] 로드맵 생성 직후 홈으로 라우팅이 불가능한 문제 해결
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
Labels: fix

#89 [Fix/quizzes] 학습에서 퀴즈 이동 시에 발생한 이슈 수정
  app/src/main/java/com/aspa/aspa/data/remote/RoadmapRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/remote/StudyFireStoreDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/RoadmapRepository.kt
  app/src/main/java/com/aspa/aspa/data/repository/StudyFireStoreRepository.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapViewModel.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/components/RoadmapDialog.kt
  app/src/main/java/com/aspa/aspa/features/state/MakeQuizState.kt
  app/src/main/java/com/aspa/aspa/features/study/StudyDetail/StudyDetailScreen.kt
  app/src/main/java/com/aspa/aspa/features/study/StudyViewModel.kt
Labels: fix

#92 [feat/mypage-provider] 마이페이지에 사용자의 소셜 provider 출력
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
Labels: feat

#93 [feat/mypage-nickname] 마이페이지에 사용자의 닉네임 출력
  app/src/main/java/com/aspa/aspa/data/remote/UserRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/AuthRepository.kt
  app/src/main/java/com/aspa/aspa/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
Labels: feat

#94 [chore/remove-unused-NicknameScreen] 사용하지 않는 닉네임 화면 삭제
  app/src/main/java/com/aspa/aspa/features/login/NicknameScreen.kt
Labels: chore

#95 [feat/confirm dialog] 로그아웃/회원탈퇴 시 확인 다이얼로그 출력
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/features/mypage/components/ConfirmDialog.kt
Labels: feat

#97 [fix/Q02-Q03] 퀴즈 관련 화면 간 라우팅 수정
  app/src/main/java/com/aspa/aspa/features/quiz/QuizResultScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/SolveQuizScreen.kt
Labels: fix

#99 [fix/no-quizzes] 퀴즈 없을 때 기본 값 처리
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
Labels: fix

#101 [ feat/logo ] 로고 반영
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/aspa/aspa/SplashScreen.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/res/drawable/aspalogo.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: feat

#102 [fix/firebase/trigger] 퀴즈 트리거 실패 개선
  firebase/functions/src/quiz/triggers.ts
Labels: fix

#105 [refactor/permission] 알림 권한 요청 퀴즈 화면에서 로그인 화면으로 이전
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/QuizViewModel.kt
Labels: refactor, fix

#112 [fix/design/quiz] 퀴즈 화면 디자인 개선
  app/src/main/java/com/aspa/aspa/features/quiz/SolveQuizScreen.kt
  app/src/main/java/com/aspa/aspa/features/quiz/component/QuestionCard.kt
  app/src/main/java/com/aspa/aspa/features/quiz/component/QuizListCard.kt
Labels: ui, fix

#98 refactor(getProvider()): 반환값 String -> Provider? 변경
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
Labels: refactor

#106 [feat/last social login] 마지막 로그인 수단 표시 기능 추가
  app/build.gradle.kts
  app/src/main/java/com/aspa/aspa/OnboardingScreen.kt
  app/src/main/java/com/aspa/aspa/SplashScreen.kt
  app/src/main/java/com/aspa/aspa/data/local/datastore/DataStoreManager.kt
  app/src/main/java/com/aspa/aspa/di/DataStoreModule.kt
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/java/com/aspa/aspa/features/login/components/SocialButton.kt
  app/src/main/java/com/aspa/aspa/features/login/navigation/LoginNavigation.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/features/navigation/AppNavHost.kt
  app/src/main/java/com/aspa/aspa/ui/components/SpeechBubble.kt
  app/src/main/res/drawable/onboarding1.jpg
  app/src/main/res/drawable/onboarding2.jpg
  app/src/main/res/drawable/onboarding3.jpg
  app/src/main/res/values/colors.xml
Labels: feat, fix

#109 [fix/fcm/remove token] 로그아웃 시 fcm 토큰 삭제
  app/src/main/java/com/aspa/aspa/data/remote/UserRemoteDataSource.kt
  app/src/main/java/com/aspa/aspa/data/repository/FcmRepository.kt
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
Labels: fix

#108 [feat/widgets] 위젯 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/aspa/aspa/DataStoreViewModel.kt
  app/src/main/java/com/aspa/aspa/OnboardingScreen.kt
  app/src/main/java/com/aspa/aspa/SplashScreen.kt
  app/src/main/java/com/aspa/aspa/core/constants/enums/Provider.kt
  app/src/main/java/com/aspa/aspa/core/constants/enums/RedirectType.kt
  app/src/main/java/com/aspa/aspa/data/local/datastore/DataStoreManager.kt
  app/src/main/java/com/aspa/aspa/data/repository/AuthRepository.kt
  app/src/main/java/com/aspa/aspa/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/aspa/aspa/features/login/AuthViewModel.kt
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
  app/src/main/java/com/aspa/aspa/features/login/components/SocialButton.kt
  app/src/main/java/com/aspa/aspa/features/login/navigation/LoginNavigation.kt
  app/src/main/java/com/aspa/aspa/features/main/MainScreen.kt
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/features/navigation/AppNavHost.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/RoadmapListScreen.kt
  app/src/main/java/com/aspa/aspa/features/roadmap/navigation/RoadmapNavigation.kt
  app/src/main/java/com/aspa/aspa/features/widget/RoadmapStatusWidgetProvider.kt
  app/src/main/java/com/aspa/aspa/features/widget/RoadmapWidgetProvider.kt
  app/src/main/res/layout/roadmap_status_widget.xml
  app/src/main/res/layout/roadmap_status_widget_init.xml
  app/src/main/res/layout/roadmap_widget.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/xml/roadmap_status_widget_info.xml
  app/src/main/res/xml/roadmap_widget_info.xml
Labels: feat

#115 [fix/route/quiz] 퀴즈 생성 직후 로드맵으로의 라우팅 불가 문제 해결
  app/src/main/java/com/aspa/aspa/ui/components/StudyNav/StudyNav.kt
Labels: fix

#120 style: 로그아웃 / 회원탈퇴 버튼 색상 변경
  app/src/main/java/com/aspa/aspa/features/mypage/MypageScreen.kt
  app/src/main/java/com/aspa/aspa/ui/theme/Theme.kt
Labels: style

#122 [fix/last-login-bubble-position] 마지막 로그인 안내 말풍선 위치 수정
  app/src/main/java/com/aspa/aspa/features/login/LoginScreen.kt
Labels: fix
